{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "intro-to-cybersecurity-dojo/cryptography/aes-cbc-poa-enc" %}
{% include "../../../../common/Dockerfile.j2" %}
