#!/usr/bin/exec-suid -- /usr/bin/python3 -I

import random
import sys
import re
import os

def randbytes(n):
	return bytes(RND.randrange(0,256) for _ in range(n))

def generate_args():
	args = set()
	for i in range(RND.randrange(500,1000)):
		letters = re.sub("[^a-z]", "", randbytes(0x200).decode('latin1')) + "ab"
		opt = letters[:RND.randrange(1,8)]
		args.add("--"+opt if len(opt)>1 else "-"+opt)

	arg_list = sorted(args)
	RND.shuffle(arg_list)
	return arg_list

print("Initializing...")

FLAG = open("/flag").read().strip()
RND = random.Random(int(re.sub("[^0-9]", "", FLAG) + "1"))
ARGS = generate_args()
FLAG_OPT = ARGS[RND.randrange(300,len(ARGS))]

if len(sys.argv) == 1:
	print("Incorrect usage! Please read the challenge man page!")
elif sys.argv[1] == "--fortune":
	os.system("/usr/games/fortune")
elif sys.argv[1] == "--version":
	print("I'm exactly the version I need to be!")
elif sys.argv[1] == FLAG_OPT:
	print("Correct usage! Your flag:", FLAG)
elif sys.argv[1] in ARGS:
	print("Valid argument, but not the one that gets you the flag! Keep searching that manpage!")
else:
	print("Incorrect usage! Please read the challenge man page!")
