{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "intro-to-cybersecurity-dojo/intercepting-communication/level-1b" %}
{% include "../../../../common/Dockerfile.j2" %}
