{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "program-security-dojo/program-security/demo-complex-corruption" %}
{% include "../../../../common/Dockerfile.j2" %}
