{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "program-security-dojo/program-security/anomalous-array-hard" %}
{% include "../../../../common/Dockerfile.j2" %}
