maintainers modified:
  - changed-files:
      - any-glob-to-any-file:
          - 'blah.yml'

dangerous:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - '.git-crypt/**'
          - '.gitattributes'
          - '**/.gitattributes'
