maintainers modified:
  - changed-files:
      - any-glob-to-any-file:
          - 'maintainers.yml'

dangerous:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - '.git-crypt/**'
          - 'tools/maintainers/ci/**'
          - 'maintainers.yml'
          - '.gitattributes'
          - '**/.gitattributes'
