#!/usr/bin/exec-suid -- /usr/bin/python3 -I

import pickle
import random
import sys
import re
import os

RND = random.Random(int(re.sub("[^0-9]", "", open("/flag").read()) + "1"))
TARGET = "/challenge/pwn"
STATE_PATH = "/tmp/.state"
PERMSTRS = { 7: "rwx", 6: "rw-", 5: "r-x", 4: "r--", 3: "-wx", 2: "-w-", 1: "--x", 0: "---" }
STRSPERM = { v:k for k,v in PERMSTRS.items() }
MAX_ROUNDS = 8

def explain_permissions(when="Current", mode=None, target=TARGET):
	u,g,o = [ int(c) for c in oct(
		os.stat(target).st_mode if mode is None else mode
	)[2:].rjust(3, "0")[-3:] ]
	print(f"""{when} permissions of "{target}": {PERMSTRS[u]}{PERMSTRS[g]}{PERMSTRS[o]}""")
	for who,what in [ ("user", u), ("group", g), ("world", o) ]:
		for bit,meaning in [ (4,"read"), (2,"write"), (1,"execute") ]:
			has = what & bit
			print(f"""{"*" if has else "-"} the {who} does{'' if has else "n't"} have {meaning} permissions""")

def next_perms(cur_perms=None, r=0):
	if cur_perms is None:
		cur_perms = os.stat(TARGET).st_mode & 0o777

	nrnd = random.Random(RND.randrange(0, 0x1000)+cur_perms+r)
	np = nrnd.randint(0,0o777)
	return np if np != cur_perms else next_perms(cur_perms=cur_perms, r=r+1)

def print_status():
	print(f"Round {ROUND+1} of {MAX_ROUNDS}!")
	print("")
	explain_permissions()
	print("")
	explain_permissions("Needed", NEEDED_PERMS)

def check():
	if os.stat(TARGET).st_mode & 0o777 == NEEDED_PERMS:
		print("You set the correct permissions!")
		with open(STATE_PATH, "wb") as o:
			pickle.dump((ROUND+1, next_perms(r=ROUND)), o)
		return True
	else:
		explain_permissions(when="NEEDED, BUT UNMET", mode=NEEDED_PERMS)
		print("")
		explain_permissions(when="CURRENT, INCORRECT")
		print("")
		print("You set the permissions incorrectly! Restarting the game!")
		os.chmod(TARGET, 0o644)
		if os.path.exists(STATE_PATH):
			os.unlink(STATE_PATH)
		return False

ROUND, NEEDED_PERMS = pickle.load(open(STATE_PATH, "rb")) if os.path.exists(STATE_PATH) else (0,next_perms(0o644,0))

if __name__ == "__main__":
	if len(sys.argv) > 1 and sys.argv[1] == "check":
		o = check()
		sys.exit(0 if o else 1)
	elif ROUND == MAX_ROUNDS:
		os.chown("/flag", 1000, 1000)
		os.chmod("/flag", 0)
		os.unlink("/challenge/bin/chmod")
		os.symlink("/usr/bin/chmod", "/challenge/bin/chmod")
		print(f"You've solved all {MAX_ROUNDS} rounds! I have changed the ownership")
		print("of the /flag file so that you can 'chmod' it. You won't be able to read")
		print("it until you make it readable with chmod!")
		print("")
		explain_permissions(when="Current", target="/flag")
	else:
		print_status()
