name: Setup challenge runtime
description: Setup challenge runtime
runs:
  using: composite
  steps:
    - name: Setup challenge runtime
      shell: bash
      run: |
        echo "::group::Disk usage"
        df -h
        echo "::endgroup::"
        sudo mkdir -p /mnt/pwn.college; [ -L /var/lib/pwn.college ] && [ "$(readlink -f /var/lib/pwn.college)" = /mnt/pwn.college ] || { [ -e /var/lib/pwn.college ] && [ ! -L /var/lib/pwn.college ] && { echo "Error: /var/lib/pwn.college exists and is not a symlink; refusing to overwrite." >&2; exit 1; }; sudo rm -f /var/lib/pwn.college 2>/dev/null || true; sudo ln -s /mnt/pwn.college /var/lib/pwn.college; }
        nix develop -c bash -lc 'echo DOCKER_HOST=$DOCKER_HOST'
