{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "fundamentals-dojo/sql-playground/sql-composite-conditions" %}
{% include "../../../../common/Dockerfile.j2" %}
