#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.9"
# dependencies = [
#   "black",
#   "jinja2",
#   "pyastyle",
#   "click",
#   "rich",
# ]
# ///

import pathlib
import sys

REPOSITORY_ROOT = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(REPOSITORY_ROOT))

from cli import cli

if __name__ == "__main__":
    cli()
