#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.9"
# dependencies = [
#   "black",
#   "jinja2",
#   "pyastyle",
#   "click",
#   "rich",
# ]
# ///

from cli import cli

if __name__ == "__main__":
    cli()
