{%- set pwn_v8_revision -%}{% include "REVISION" %}{%- endset -%}
{%- set pwn_v8_args_cache_key = "v8-learning-foundation" -%}
{%- set pwn_challenge_cache_key = "ramp-v8-cage-boundary" -%}
{% include "../../../common/Dockerfile.j2" %}
