FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 && \
    rm -rf /var/lib/apt/lists/*

COPY stuff-stocking /challenge/stuff-stocking
COPY --chmod=755 <<'EOF' /challenge/init-stuff-stocking.sh
#!/bin/sh

/challenge/stuff-stocking &
EOF

RUN cd /challenge && ln -s ./init-stuff-stocking.sh ./.init
