#!/usr/bin/exec-suid -- /bin/bash -p

if [ ! -t 2 ] && [ "$(realpath --relative-to=/proc/$$ /proc/$$/fd/2)" != "$(realpath --relative-to=/proc/$PPID /proc/$PPID/fd/2)" ]
then
	PTS=$(
		ps -g $(ps -p "$$" -o sid=) --no-headers -o pid |
		xargs -IPID -n1 ls /proc/PID/fd/ -l 2>/dev/null |
		grep pts | sed -e "s/.* //" | sort -u | tail -n1
	)
	fold -s > $PTS <<< "You are redirecting standard error *of /challenge/planet*! Instead, you must redirect standard error of 'hack'. This must be done *before* any |. The right side of the pipe is a different command, with its own redirection, than the left side!"
fi

read CORRECT < /challenge/.challenge-key-stdout
read ATTEMPT < <(tail -n 1)
if [ "$CORRECT" == "$ATTEMPT" ]
then
	cp /challenge/.challenge-key-solve /challenge/.planet
else
	fold -s >&2 <<< "Are you sure you're properly redirecting /challenge/hack's standard output into '/challenge/planet'?"
fi
