#!/usr/bin/exec-suid -- /bin/python3 -I

import sys

import base64


def reverse_string(s):
    return s[::-1]


print("Enter the password:")
entered_password = sys.stdin.buffer.read1()
correct_password = b"\xd1\xa6; E_\xa6\x9d"

print(f"Read {len(entered_password)} bytes.")


entered_password = bytes.fromhex(entered_password.decode("l1"))
entered_password = entered_password[::-1]
entered_password = bytes.fromhex(entered_password.decode("l1"))
entered_password = entered_password[::-1]

correct_password = base64.b64encode(correct_password)
correct_password = correct_password[::-1]
correct_password = correct_password[::-1]
correct_password = base64.b64encode(correct_password)


if entered_password == correct_password:
    print("Congrats! Here is your flag:")
    print(open("/flag").read().strip())
else:
    print("Incorrect!")
    sys.exit(1)
