#!/usr/bin/exec-suid -- /bin/bash -p

if [ ! -p /dev/stdout ]
then
	fold -s <<< "The stdout of /challenge/run does not seem to point to a FIFO!" >&2
	exit 1
fi

if [ ! -f /tmp/.redirected ]
then
	fold -s <<< "You did not redirect /challenge/run's stdout to /tmp/flag_fifo!" >&2
	exit 2
fi

fold -s <<< "You've correctly redirected /challenge/run's stdout to a FIFO at /tmp/flag_fifo! Here is your flag:"
cat /flag
