#!/bin/bash

if ls -l /proc/$$/fd/{0,1,2} | grep -vq pts
then
	fold -s 1>&2 <<< "It looks like you may have chained the pwn command with a pipe or other input redirection method. In this level, you must script the commands to run one after the other, without piping or redirection!"
	exit
fi

if [ "$1" == ";" ]
then
	fold -s <<< "It looks like you wrapped your semicolon in quotes, which causes the shell to treat it differently. Just put the raw ;!"
	exit
fi

touch /tmp/.pwn
