#!/usr/bin/exec-suid --real -- /usr/bin/python -I

import psutil
import socket
import time
import os

from dojjail import Host, Network

flag = open("/flag").read()
parent_process = psutil.Process(os.getppid())

class ServerHost(Host):
    def entrypoint(self):
        server_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        server_socket.bind(("0.0.0.0", 31337))
        while True:
            try:
                client_message, (client_host, client_port) = server_socket.recvfrom(1024)
                if client_message.strip() == b"ACTION?":
                    server_socket.sendto(b"NONE", (client_host, client_port))
            except ConnectionError:
                continue

class ClientHost(Host):
    def entrypoint(self):
        client_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        client_socket.bind(("0.0.0.0", 31338))
        while True:
            try:
                client_socket.sendto(b"ACTION?", ("10.0.0.3", 31337))
                message, (peer_host, peer_port) = client_socket.recvfrom(1024)
                if peer_port == 31337 and message.strip() == b"FLAG":
                    print(f"YOUR FLAG: {flag}")

                time.sleep(1)
            except ConnectionError:
                continue

user_host = Host("ip-10-0-0-1", privileged_uid=parent_process.uids().effective)
client_host = ClientHost("ip-10-0-0-2")
server_host = ServerHost("ip-10-0-0-3")
network = Network(hosts={user_host: "10.0.0.1", client_host: "10.0.0.2", server_host: "10.0.0.3"}, subnet="10.0.0.0/24")
network.run()

user_host.interactive(environ=parent_process.environ())
