{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "program-security-dojo/dynamic-allocator-misuse/level-18-0" %}
{% include "../../../../common/Dockerfile.j2" %}
