name: Determine modified challenges
description: Determine modified challenges and group them by top-level directory.
outputs:
  modified_since_ref:
    description: Base ref challenges have been modified since.
    value: ${{ steps.resolve-ref.outputs.ref }}
  challenges:
    description: Top-level challenge groups.
    value: ${{ steps.resolve-challenges.outputs.challenges }}
runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      id: resolve-ref
      with:
        script: |
          let ref = "";
          if (context.eventName === "pull_request") {
            ref = context.payload.pull_request.base.sha;
          } else if (context.eventName === "push") {
            const workflowFile = process.env.GITHUB_WORKFLOW_REF.split("@")[0].split("/").pop();
            const branch = context.ref.replace("refs/heads/", "");
            const { owner, repo } = context.repo;
            const runs = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: workflowFile,
              branch,
              status: "success",
              per_page: 1,
            });
            const [latest] = runs.data.workflow_runs;
            ref = latest ? latest.head_sha : "";
          }
          core.setOutput("ref", ref);

    - uses: actions/checkout@v4
      if: ${{ steps.resolve-ref.outputs.ref != '' }}
      with:
        fetch-depth: 0

    - uses: actions/checkout@v4
      if: ${{ steps.resolve-ref.outputs.ref == '' }}

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        cache-dependency-glob: tools/pwnshop/**

    - uses: actions/github-script@v7
      id: resolve-challenges
      env:
        MODIFIED_SINCE: ${{ steps.resolve-ref.outputs.ref }}
      with:
        script: |
          const { execFileSync } = require("child_process");
          const ref = process.env.MODIFIED_SINCE || "";
          const output = execFileSync("./pwnshop", ["list", "./challenges", `--modified-since=${ref}`], {
            stdio: ["ignore", "pipe", "inherit"],
          })
            .toString()
            .trim();
          const challenges = Array.from(
            new Set(output.split("\n").map((line) => line.trim().split("/")[0]).filter(Boolean)),
          ).sort();
          core.setOutput("challenges", JSON.stringify(challenges));
