FROM python:3.13

WORKDIR /challenge

RUN apt-get update && apt-get install -y --no-install-recommends openssh-client && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    flask==3.0.3 \
    requests==2.32.3 \
    cryptography==44.0.0

COPY north_poole.py santa.py elf.py children.py init-northpoole.sh ./
RUN cd /challenge && ln -s ./init-northpoole.sh ./.init
