{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "system-security-dojo/speculative-execution/babyarch-parsemultipage" %}
{% include "../../../../common/Dockerfile.j2" %}
