#!/usr/bin/exec-suid -- /bin/bash -p

LEVEL_FILE="/challenge/.state"

if [ -f "$LEVEL_FILE" ]; then
    LEVEL=$(cat "$LEVEL_FILE")
else
    LEVEL=1
    echo "Starting level $LEVEL."
fi

RANDOM=$(cksum /flag  | awk '{print $1}')
CANDIDATES=(
        "/"
        "/tmp"
        "/var"
        "/etc"
        "/sys"
        "/home"
        "/usr/bin"
        "/var/log"
        "/sys/kernel"
        "/etc/apt/sources.list.d"
        "/usr/include"
        "/usr/share/zoneinfo/posix/Asia"
        "/usr/aarch64-linux-gnu/include/gnu"
        "/usr/share/doc"
        "/usr/share/doc/fontconfig"
        "/usr/share/build-essential"
        "/var/lib/apt/lists"
)

FILTERED=()
for dir in "${CANDIDATES[@]}"; do
    if [[ -d "$dir" ]]; then
        FILTERED+=("$dir")
    fi
done
CANDIDATES=("${FILTERED[@]}")

for ((i=${#CANDIDATES[@]}-1; i>0; i--)); do
    j=$((RANDOM % (i+1)))
    tmp="${CANDIDATES[i]}"
    CANDIDATES[i]="${CANDIDATES[j]}"
    CANDIDATES[j]="$tmp"
done

NEEDED=${CANDIDATES[ $LEVEL ]}

if [ "$PWD" != "$NEEDED" ]
then
        echo -e "${COLOR_RED}Incorrect...${COLORLESS}"
        echo "You are not currently in the $NEEDED directory."
        echo 'Please use the `cd` utility to change directory appropriately.'
        exit 1
fi

if [ "${0:0:1}" != "/" ]
then
        echo -e "${COLOR_RED}Incorrect...${COLORLESS}"
        echo "You did not call this challenge using an absolute path!"
        echo "An absolute path is anchored at the root of the filesystem, so it starts with /"
        exit 1
fi

echo -e "${COLOR_GREEN}Correct!!!${COLORLESS}"
echo "$0 is an absolute path, invoked from the right directory!"
((LEVEL++))

echo "$LEVEL" > "$LEVEL_FILE"

if [ "$LEVEL" -eq 6 ]
then
        rm $LEVEL_FILE
        echo "Here is your flag:"
        /bin/cat /flag
        exit 0
fi

echo "Moving on to level $LEVEL"
NEEDED=${CANDIDATES[ $LEVEL ]}
echo "Please use the \`cd\` utility to change directory to $NEEDED"
