#!/bin/bash

/bin/fold -w $(/bin/tput cols) -s <<END
You cannot solve this challenge using /challenge/run.
To solve this challenge, you must set the PWN variable to the value "COLLEGE YEAH".
The challenge will detect this and give you the flag!
END
