{%- set pwn_v8_revision -%}{% include "REVISION" %}{%- endset -%}
{%- set pwn_v8_args_cache_key = "chain-issue-380397544-350292240" -%}
{%- set pwn_challenge_cache_key = "chain-issue-380397544-350292240" -%}
{% include "../../../common/Dockerfile.j2" %}
