#!/usr/bin/exec-suid -- /bin/bash -p

read -a ARGS < /tmp/.last_arg

if [ "$PWD" != "/challenge/files" ]
then
	fold -s <<< "Error: please run with a working directory of /challenge/files!"
	exit 1
fi

if [ "${#ARGS[@]}" -eq 0 ]
then
	fold -s <<< "Error: you called this command with no arguments! Please call me with one argument."
	exit 2
fi

if [ "${#ARGS[@]}" -gt 1 ]
then
	fold -s <<< "Error: you called this command with more than 1 argument (pre-globbing)! Please call me with one argument."
	exit 3
fi

if [[ "${ARGS[0]}" != *"["* ]]
then
	fold -s <<< "Error: you did not use a square bracket glob..."
	exit 4
fi

if [ "$1" == "file_a" ] && [ "$2" == "file_b" ] && [ "$3" == "file_h" ] && [ "$4" == "file_s" ]
then
	fold -s <<< "You got it! Here is your flag!"
	cat /flag
else
	fold -s <<< "Your expansion did not expand to the requested files (file_a, file_b, file_h, and file_s). Instead, it expanded to:"
	echo "$@"
fi
