FROM ubuntu:24.04

RUN apt update && \
    apt install -y --no-install-recommends \
        build-essential libseccomp-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /challenge
COPY northpole-relay.c .
RUN gcc -o ./northpole-relay ./northpole-relay.c -lseccomp && \
    chmod 4755 ./northpole-relay
