#!/usr/bin/exec-suid -- /bin/python3 -I

import sys

import base64


def reverse_string(s):
    return s[::-1]


def encode_to_bits(s):
    return b"".join(format(c, "08b").encode("latin1") for c in s)


print("Enter the password:")
entered_password = sys.stdin.buffer.read1()
correct_password = b"\xb8\xc9\xbc\xd2P\xed\x8d\xa8"

print(f"Read {len(entered_password)} bytes.")


entered_password = base64.b64decode(entered_password.decode("l1"))
entered_password = bytes.fromhex(entered_password.decode("l1"))
entered_password = bytes.fromhex(entered_password.decode("l1"))
entered_password = entered_password[::-1]

correct_password = encode_to_bits(correct_password)
correct_password = base64.b64encode(correct_password)
correct_password = correct_password[::-1]
correct_password = correct_password[::-1]


if entered_password == correct_password:
    print("Congrats! Here is your flag:")
    print(open("/flag").read().strip())
else:
    print("Incorrect!")
    sys.exit(1)
