#!/usr/bin/exec-suid -- /bin/bash -p

if [ -f /home/hacker/delete_me ]
then
	fold -s <<< "It looks like /home/hacker/delete_me still exists! rm it."
else
	fold -s <<< "Excellent removal. Here is your reward:"
	cat /flag
fi
