name: Move runtime storage
description: Move pwn.college challenge runtime storage to /mnt for more space.
runs:
  using: composite
  steps:
    - name: Move storage
      shell: 'nix develop -c bash -euo pipefail {0}'
      run: |
        echo "::group::Disk usage"
        df -h
        echo "::endgroup::"
        sudo rm -rf /var/lib/pwn.college
        sudo mkdir -p /mnt/pwn.college
        sudo ln -s /mnt/pwn.college /var/lib/pwn.college
