{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "program-security-dojo/program-security/demo-cooking-with-canaries" %}
{% include "../../../../common/Dockerfile.j2" %}
