{% set challenge_image = "pwncollege/challenge-secure-chat-3" %}
{% set challenge_path = "intro-to-cybersecurity-dojo/integrated-security/secure-chat-3" %}
{% include "../../../../common/Dockerfile.j2" %}
