#!/usr/bin/exec-suid -- /bin/bash -p

fold -s <<< "I could give you the flag... but I won't, until this process exits. Remember, you can force me to exit with Ctrl-C. Try it now!"

function flag {
	echo
	fold -s <<< "Good job! You have used Ctrl-C to interrupt this process! Here is your flag:"
	cat /flag
}

trap flag SIGINT
sleep 6h
