#!/usr/bin/exec-suid -- /usr/bin/python3 -I

from Crypto.Cipher import AES
from Crypto.Util.Padding import pad
from Crypto.Random import get_random_bytes

flag = open("/flag", "rb").read().strip()
key = get_random_bytes(16)
cipher = AES.new(key=key, mode=AES.MODE_ECB)

while True:
    pt = bytes.fromhex(input("Data? ").strip()) + flag
    ct = cipher.encrypt(pad(pt, cipher.block_size))
    print(f"Ciphertext: {ct.hex()}")
