{%- set pwn_v8_revision -%}{% include "REVISION" %}{%- endset -%}
{%- set pwn_v8_args_cache_key = "ramp-maglev-tiering-state" -%}
{%- set pwn_challenge_cache_key = "ramp-maglev-tiering-state" -%}
{% include "../../../common/Dockerfile.j2" %}
