#!/usr/bin/exec-suid -- /bin/bash -p

function resumed {
    trap 'unset _IN_RESUMED_HANDLER' RETURN

    if [[ -n "$_IN_RESUMED_HANDLER" ]]; then
        return
    fi
    _IN_RESUMED_HANDLER=1

    if [[ $(ps -o stat= -p $$) == *+* ]]; then
        sleep 0.12
        if [[ $(ps -o stat= -p $$) == *+* ]]; then
            fold -s <<< "You resumed me into the foreground from suspension! Please resume me into the background, and *then* swap me into the foreground directly from there (or press Enter, and I'll exit)."
            read A
            unset _IN_RESUMED_HANDLER
            exit
        fi
    fi

    echo
    echo
    echo
    fold -s <<< "Yay, I'm now running the background! Because of that, this text will probably overlap weirdly with the shell prompt. Don't panic; just hit Enter a few times to scroll this text out. After that, resume me into the foreground with 'fg'; I'll wait."

    until [[ $(ps -o stat= -p $$) == *+* ]]; do sleep 0.1; done

    fold -s <<< "YES! Great job! I'm now running in the foreground. Hit Enter for your flag!"
    read A
    cat /flag
    unset _IN_RESUMED_HANDLER
    exit
}
trap resumed SIGCONT

[[ "$BASH_EXECUTION_STRING" == .* ]] && exec -a bash /bin/bash $BASH_SOURCE

fold -s <<< "To pass this level, you need to suspend me, resume the suspended process in the background, and *then* foreground it without re-suspending it! You can background me with Ctrl-Z (and resume me in the background with 'bg') or, if you're not ready to do that for whatever reason, just hit Enter and I'll exit!"
read A