#!/bin/bash

if [ "$(id -u)" = 0 ]
then
	echo "Congratulations, you have run this command as root! Here is your flag:"
	cat /flag
else
	fold -s <<< "You are the $(whoami) user... Run /challenge/run with sudo to read the flag."
fi
