{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "program-security-dojo/reverse-engineering/when-the-cow-says-moo" %}
{% include "../../../../common/Dockerfile.j2" %}
