{%- extends "../../common/Dockerfile.j2" -%}
{%- block additional_packages %}{{ super() }} build-essential figlet toilet-fonts{% endblock -%}
{%- block setup -%}
RUN <<'EOF'
set -eu
gcc -O0 -w -o /challenge/cimg /challenge/cimg.c
chmod 755 /challenge/cimg
rm -f /challenge/cimg.c
chmod 4755 /challenge/generate_flag_image
rm -f /challenge/Dockerfile /challenge/.setup
EOF
{%- endblock -%}
