{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "program-security-dojo/return-oriented-programming/demo-take-it-or-leave-it" %}
{% include "../../../../common/Dockerfile.j2" %}
