name: Report docker storage
description: Emit disk and Docker storage usage.
runs:
  using: composite
  steps:
    - name: Report docker storage
      shell: 'nix develop -c bash -euo pipefail {0}'
      run: |
        echo "::group::Disk usage"
        df -h
        echo "::endgroup::"
        echo "::group::Docker system usage"
        docker system df
        docker system df -v
        echo "::endgroup::"
        echo "::group::Docker storage contents"
        sudo sh -c 'du -sh /var/lib/docker/* 2>/dev/null || true'
        echo "::endgroup::"
        echo "::group::Containerd storage contents"
        sudo sh -c 'du -sh /var/lib/containerd/* 2>/dev/null || true'
        echo "::endgroup::"
