{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "intro-to-cybersecurity-dojo/integrated-security/decrypt-overflow-ecb" %}
{% include "../../../../common/Dockerfile.j2" %}
