#!/usr/bin/exec-suid -- /usr/bin/python3 -I

import sys
import re
import os

FLAG = open("/flag").read().strip()
LETTERS = re.sub("[^a-z]", "", FLAG[FLAG.index('{'):]) + "ab"
NUMBERS = re.sub("[^0-9]", "", FLAG[FLAG.index('{'):]) + "1"
OPT,ARG = LETTERS[:6], NUMBERS[:3]

if len(sys.argv) == 1:
	print("Incorrect usage! Please read the hidden challenge man page!")
elif sys.argv[1] == "--fortune":
	os.system("/usr/games/fortune")
elif sys.argv[1] == "--version":
	print("I'm exactly the version I need to be!")
elif sys.argv[1:] == ["--"+OPT, ARG]:
	print("Correct usage! Your flag:", FLAG)
else:
	print("Incorrect usage! Please read the hidden challenge man page!")
