{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "archive-dojo/reverse-engineering/powered-by-yancode-hard" %}
{% include "../../../../common/Dockerfile.j2" %}
