# syntax=docker/dockerfile:1

FROM pwncollege/challenge-legacy:latest

# https://github.com/pwncollege/official-dojos
WORKDIR /opt/dojos

# Getting Started
ADD https://github.com/pwncollege/welcome-dojo ./welcome-dojo
ADD https://github.com/pwncollege/linux-luminarium ./linux-luminarium
ADD https://github.com/pwncollege/computing-101 ./computing-101
ADD https://github.com/pwncollege/fundamentals-dojo ./fundamentals-dojo

# Core Material
ADD https://github.com/pwncollege/intro-to-cybersecurity-dojo ./intro-to-cybersecurity-dojo
ADD https://github.com/pwncollege/program-security-dojo ./program-security-dojo
ADD https://github.com/pwncollege/system-security-dojo ./system-security-dojo
ADD https://github.com/pwncollege/software-exploitation-dojo ./software-exploitation-dojo

# Official Community dojos
ADD https://github.com/pwncollege/xnu-dojo ./xnu-dojo
ADD https://github.com/pwncollege/injection-dojo ./injection-dojo
ADD https://github.com/pwncollege/arm-dojo ./arm-dojo
# ADD https://github.com/prathamgupta36/cryptomania ./cryptomania
ADD https://github.com/pwncollege/windows-dojo ./windows-dojo
# ADD https://github.com/robwaz/demo-dojo ./demo-dojo

# Archives
ADD https://github.com/pwncollege/archive-dojo ./archive-dojo
# ADD https://github.com/pwncollege/ctf-archive ./ctf-archive

COPY --chmod=755 <<EOF /challenge/.init
#!/bin/bash
set -eou pipefail

if [ ! -d "$CHALLENGE_PATH" ]; then
    echo "[*] Challenge path $CHALLENGE_PATH does not exist!"
    exit 1
fi

rm /challenge/.init

find "$CHALLENGE_PATH" -mindepth 1 -maxdepth 1 ! -name '_*' -exec cp -aL {} /challenge \;

instance=$(find "$CHALLENGE_PATH" -mindepth 1 -maxdepth 1 -name '_*' -type d -print0 | sort -z | head -zn1 | tr -d '\0')
if [ -n "$instance" ]; then
    cp -aL "$instance/.init" /challenge/.init
fi

chown -R 0:0 /challenge
chmod -R 4755 /challenge

if [ -x /challenge/.init ]; then
    exec /challenge/.init
fi
EOF

ARG CHALLENGE_PATH="/opt/dojos/{{ challenge_path }}"
ENV CHALLENGE_PATH="${CHALLENGE_PATH}"
