name: Test challenges
description: Test challenges.
inputs:
  challenges:
    description: Top-level challenge group.
    required: true
  modified_since_ref:
    description: Base ref challenges have been modified since.
    required: false
    default: ""
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      if: ${{ inputs.modified_since_ref != '' }}
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        cache-dependency-glob: tools/**

    - name: Install git-crypt
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y git-crypt

    - name: Remove encrypted directories
      shell: bash
      run: |
        git crypt status -e | sed -e "s/ *encrypted: //" | xargs dirname | xargs rm -rf

    - name: Test challenges
      shell: bash
      env:
        CHALLENGES_DIR: challenges/${{ inputs.challenges }}
        MODIFIED_SINCE: ${{ inputs.modified_since_ref }}
      run: |
        set -euo pipefail
        JOBS=$(( $(nproc) * 2 ))
        if [ -f "$CHALLENGES_DIR/dojo.yml" ]; then
          echo "::group::Validating dojo.yml"
          ./tools/dojo/parse-dojo-yml "$CHALLENGES_DIR/dojo.yml"
          echo "::endgroup::"
        fi
        echo "::group::Challenges to be tested"
        ./pwnshop list "$CHALLENGES_DIR" --modified-since="$MODIFIED_SINCE"
        echo "::endgroup::"
        echo "::group::Testing challenges"
        ./pwnshop test --jobs "$JOBS" --modified-since="$MODIFIED_SINCE" "$CHALLENGES_DIR"
        echo "::endgroup::"
