{%- set pwn_v8_revision -%}{% include "REVISION" %}{%- endset -%}
{%- set pwn_v8_args_cache_key = "v8-learning-2026-wasmfx" -%}
{%- set pwn_challenge_cache_key = "ramp-wasmfx-cont-native-leak" -%}
{% include "../../../common/Dockerfile.j2" %}
