#!/usr/bin/exec-suid -- /bin/python3 -I

import sys


def reverse_string(s):
    return s[::-1]


print("Enter the password:")
entered_password = sys.stdin.buffer.read1()
correct_password = b"\x06\x08\xd1\x16+h\xacy"

print(f"Read {len(entered_password)} bytes.")


entered_password = entered_password[::-1]
entered_password = bytes.fromhex(entered_password.decode("l1"))


if entered_password == correct_password:
    print("Congrats! Here is your flag:")
    print(open("/flag").read().strip())
else:
    print("Incorrect!")
    sys.exit(1)
