#!/usr/bin/exec-suid --environ=all -- /bin/bash -p

/bin/fold -s <<< "Trying to remove /flag..."
rm -f /flag

if [ -f /flag ]
then
	/bin/fold -s <<< "The flag is still there! I might as well give it to you!"
	/bin/cat /flag
else
	/bin/fold -s <<< "Uh oh, looks like I successfully removed the flag! That means you did not properly set PATH to keep me from finding 'rm'. Since the flag is gone, you will need to re-launch the challenge from the module page! Better luck next time."
fi
