#!/usr/bin/exec-suid -- /bin/bash -p

if ps -ef | grep -q '[d]ont_run'
then
	fold -s <<< "Nope! /challenge/dont_run is still running! You gotta terminate it before I give you the flag!"
	exit
fi

fold -s <<< "Great job! Here is your payment:"
cat /flag
