#!/usr/bin/exec-suid -- /usr/bin/python3 -I

import time
import os

def entry_count(path):
    try:
        return len(os.listdir(path))
    except FileNotFoundError:
        return 0

flag = open("/flag").read()

while True:
    if entry_count("/") > 10 or entry_count("/usr") > 3 or entry_count("/etc") > 5 or os.path.exists("/flag"):
        print("Looks like you haven't wiped the system! We'll check again in 5 seconds...")
    else:
        print("YES! You wiped it, you wild hacker! The flag is yours:")
        print(flag)
        break

    time.sleep(5)
