{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "intro-to-cybersecurity-dojo/intercepting-communication/udp-spoof-host" %}
{% include "common/Dockerfile.j2" %}
