{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "program-security-dojo/return-oriented-programming/level-4-0" %}
{% include "../../../../common/Dockerfile.j2" %}
