{% extends "../../common/Dockerfile.j2" %}

{% block challenge %}
FROM kernel AS syscall
RUN <<'EOF'
echo 'asmlinkage long sys_hello(const char __user *name);' >> include/linux/syscalls.h
echo '470 common hello sys_hello' >> arch/x86/entry/syscalls/syscall_64.tbl
echo '
SYSCALL_DEFINE1(hello, const char __user *, name)
{
    return -ENOSYS;
}' >> kernel/sys.c

make -j"$(nproc)"
EOF

FROM tools AS guest
COPY hello.c /tmp/hello.c
RUN gcc -static -Os -Wall -Wextra -Werror /tmp/hello.c -o /tmp/hello

FROM initramfs
COPY --from=syscall --chown=1000:1000 /usr/src/linux /usr/src/linux
COPY --from=syscall --chown=1000:1000 /var/cache/ccache /var/cache/ccache
COPY --from=guest --chmod=755 /tmp/hello /usr/src/initramfs/usr/bin/hello
COPY --chmod=755 init /usr/src/initramfs/init

ADD --chmod=6755 https://github.com/pwncollege/exec-suid/releases/latest/download/exec-suid /usr/bin/exec-suid
COPY --chmod=4755 run /challenge/run
{% endblock %}
