{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "intro-to-cybersecurity-dojo/web-security/cmdi-touch-blind" %}
{% include "../../../../common/Dockerfile.j2" %}
