#!/usr/bin/exec-suid -- /bin/python3 -I

import sys

import base64


def reverse_string(s):
    return s[::-1]


print("Enter the password:")
entered_password = sys.stdin.buffer.read1()
correct_password = b"\xb5\xc1\xcbx\x98\xa3\xa8\x84"

print(f"Read {len(entered_password)} bytes.")


correct_password = correct_password[::-1]
correct_password = correct_password[::-1]
correct_password = base64.b64encode(correct_password)
correct_password = base64.b64encode(correct_password)


if entered_password == correct_password:
    print("Congrats! Here is your flag:")
    print(open("/flag").read().strip())
else:
    print("Incorrect!")
    sys.exit(1)
