{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "intro-to-cybersecurity-dojo/reverse-engineering/cimg-operations-c" %}
{% include "../../../../common/Dockerfile.j2" %}
