{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "intro-to-cybersecurity-dojo/intercepting-communication/dos-3" %}
{% include "../../../../common/Dockerfile.j2" %}
