{% set challenge_image = "pwncollege/challenge-legacy:latest" %}
{% set challenge_path = "computing-101/building-a-web-server/concurrent-post-server" %}
{% include "../../../../common/Dockerfile.j2" %}
