name: Check Maintainers

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "maintainers.yml"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix

      - name: Check Maintainers
        shell: 'nix shell nixpkgs#uv nixpkgs#gnupg --command bash --noprofile --norc -euo pipefail {0}'
        run: tools/maintainers/check-maintainers ./maintainers.yml
