FROM python:3.13 AS builder

WORKDIR /build
COPY generate_list.py .
RUN ./generate_list.py > ./check-list && \
    chmod 4755 ./check-list

FROM ubuntu:24.04
RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 binutils && \
    rm -rf /var/lib/apt/lists/*
COPY --from=builder /build/check-list /challenge/check-list
